# Generated by Django 4.1 on 2022-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto_corto', models.CharField(max_length=40)),
                ('texto_largo', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
