# Generated by Django 4.1 on 2022-09-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=20)),
                ('nombre_autor', models.CharField(max_length=20)),
                ('nombre_editorial', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
    ]
