# Generated by Django 4.1 on 2022-10-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0002_busqueda'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaFiltrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=20)),
                ('nombre_autor', models.CharField(max_length=20)),
            ],
        ),
    ]
