# Generated by Django 4.1 on 2022-10-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0003_busquedafiltrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=20)),
                ('equipo', models.CharField(max_length=20)),
                ('titulos', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.CharField(max_length=20)),
                ('album', models.CharField(max_length=20)),
                ('artista', models.CharField(max_length=20)),
                ('comentarios', models.CharField(max_length=80)),
                ('premios', models.CharField(max_length=40)),
            ],
        ),
    ]
