# Generated by Django 4.1 on 2022-10-12 21:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0004_futbol_musica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busquedafiltrada',
            name='nombre_autor',
            field=ckeditor.fields.RichTextField(max_length=20),
        ),
    ]
