# Generated by Django 4.1 on 2022-10-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0005_alter_busquedafiltrada_nombre_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedafiltrada',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
