# Generated by Django 4.1 on 2022-10-12 23:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0006_busquedafiltrada_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busquedafiltrada',
            name='nombre_autor',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
