# Generated by Django 4.1 on 2022-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0007_alter_busquedafiltrada_nombre_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedafiltrada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
