# Generated by Django 4.1 on 2022-10-14 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0010_alter_busquedafiltrada_nombre_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedafiltrada',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
